#!/usr/bin/env bash
# Precompile JSX → plain JS so the site does not ship Babel-in-browser.
# After editing trium/*.jsx, re-run this script (and scripts/prerender.sh if the shell should refresh).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p trium/build

compile() {
  local out="$1"
  shift
  local tmp
  tmp="$(mktemp /tmp/trium-jsx-XXXXXX.jsx)"
  cat "$@" > "$tmp"
  npx --yes esbuild "$tmp" \
    --jsx=transform \
    --jsx-factory=React.createElement \
    --jsx-fragment=React.Fragment \
    --format=iife \
    --target=es2018 \
    --outfile="$out"
  rm -f "$tmp"
  local banner="/* generated by scripts/compile.sh — edit trium/*.jsx, then re-run */\n"
  printf '%b' "$banner" | cat - "$out" > "$out.tmp" && mv "$out.tmp" "$out"
  echo "wrote $out ($(wc -c < "$out") bytes)"
}

compile trium/build/landing.js \
  trium/icons.jsx \
  trium/sections-top.jsx \
  trium/sections-mid.jsx \
  trium/sections-bottom.jsx \
  trium/app.jsx

compile trium/build/portal.js \
  trium/icons.jsx \
  trium/portal.jsx
